# templates/secret-postgres.yaml
{{- if and .Values.postgres.enabled (not .Values.postgres.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "mcp-stack.postgresSecretName" . | trim }}"
type: Opaque
stringData:
  # add the keys the Postgres image needs
  POSTGRES_USER:      {{ .Values.postgres.credentials.user      | quote }}
  POSTGRES_PASSWORD:  {{ .Values.postgres.credentials.password  | quote }}
  POSTGRES_DB:        {{ .Values.postgres.credentials.database  | quote }}
{{- end }}
