{{- if .Values.mcpFastTimeServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  # <release>-mcp-stack-mcp-fast-time-server
  name: {{ include "mcp-stack.fullname" . }}-mcp-fast-time-server
  labels:
    {{- include "mcp-stack.labels" . | nindent 4 }}
    app: {{ include "mcp-stack.fullname" . }}-mcp-fast-time-server
spec:
  type: ClusterIP
  selector:
    app: {{ include "mcp-stack.fullname" . }}-mcp-fast-time-server
  ports:
    - name: http
      protocol: TCP
      port: 80                    # stable service port
      targetPort: {{ .Values.mcpFastTimeServer.port }}   # containerPort (8080)
{{- end }}
